### ISSUE TITLE
Meeting Minutes 

### ISSUE THREAD

**Issue by SsoyeonLee** [prafulrpatel389/F7204_HEADS-UP#29]
# Task Details

- [x]  Meeting Minutes for 08/28/17
- [x]  Meeting Minutes for 08/30/17
- [x]  Meeting Minutes for 09/06/17
- [x]  Meeting Minutes for 09/08/17
